---
box: "ubuntu/vivid64"
devstack-1:
  host_name: devstack-1
  ip: "192.168.33.101"
  memory: 4096
  cpus: 2
devstack-1-compute:
  host_name: devstack-1-compute
  ip: "192.168.33.102"
  memory: 1024
  cpus: 1
