---
box: "ubuntu/vivid64"
devstack_controller:
  host_name: devstack.controller.dev
  ip: "192.168.33.101"
  memory: 4096
  cpus: 2
devstack_compute:
  host_name: devstack.compute.dev
  ip: "192.168.33.102"
  memory: 1024
  cpus: 1
